version: "3.9"
services:
  web:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/backend.overpaper.com/fullchain.pem:/etc/letsencrypt/live/backend.overpaper.com/fullchain.pem:ro
      - /etc/letsencrypt/live/backend.overpaper.com/privkey.pem:/etc/letsencrypt/live/backend.overpaper.com/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front
networks:
  front:
    external: true